name: dresscabinet
description: E-commerce app

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  iconify_flutter: ^0.0.4
  carousel_slider: ^4.1.1
  fluttertoast: ^8.0.9
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.2.2
  shared_preferences: ^2.0.15
  pinch_zoom: ^1.0.0
  flutter_svg: ^1.1.5
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.1.6
  share_plus: ^5.0.0
  country_codes: ^2.2.0
  country_icons: ^2.0.2
  flutter_credit_card: ^3.0.4
  http: ^0.13.5
  intl: ^0.17.0
  sqflite: ^2.2.0+3
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon.png"
